services:
  app:
    build: .
    ports:
      - "8080:8000"
    depends_on:
      - db

  db:
    image: postgres:15.3
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=todoapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

volumes:
  pgdata:
